### ISSUE TITLE
All Day Events display 2 Days

### ISSUE THREAD

**Issue by butchewing** [MilanKacurak/FormatGoogleCalendar#6]
Events marked "All Day" in the Google Calendar are displaying at two days in the event list. Google converts the "All Day" to something like: `Mon, September 5, 12am – Tue, September 6, 12am`. How can I prevent all day events from displaying two days like: `September 4, 2016 – September 5, 2016`?

**Comment by alexmurray4** [comment]
Also having the same issue... has this been fixed yet?

**Comment by alexmurray4** [comment]
@MilanKacurak it still looks like it is displaying across two days as it now shows `September 5, 2016 from 12:00PM - 12:00AM` on the 6th of September for a event that is on the 5th of September. I think this is because it starts on the 5th at 12pm - which it should be 12:00am and go through to 11:59pm rather than 12am (making it 12:00am to 11:59pm). That way it should shouldn't display over 2 days. Any chance of a fix for this? Thanks!

**Comment by covertmichael** [comment]
I am having the same issue as @alexmurray4. I am unsure of how to fix it. Any chance you have an idea @MilanKacurak? Thanks for the support!

**Comment by MilanLund** [comment]
@alexmurray4 @covertmichael Thanks for reporting all the issues. I found out there are more ways on how to create an all day event. I hope, the fix will do the job for you. Keep testing!
